services:
  - type: web
    name: xlsx-server
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY_HERE
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
